const { withAppBuildGradle } = require('expo/config-plugins');

// android/ is gitignored and fully regenerated by `expo prebuild`, so Expo's
// default template (release build signed with the debug keystore) silently
// wins back on every prebuild unless patched here. The production upload
// keystore itself lives outside the repo (C:/Users/<user>/keystore/bes-
// upload-new.jks) with its credentials in the user's global
// ~/.gradle/gradle.properties as BES_UPLOAD_STORE_FILE / _STORE_PASSWORD /
// _KEY_ALIAS / _KEY_PASSWORD — never committed, matching *.jks in
// mobile/.gitignore.
//
// Defensive on purpose: if a future Expo/RN template changes this
// generated text, fail the prebuild loudly rather than silently shipping a
// debug-signed release bundle.
const SIGNING_CONFIGS_FROM = `signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }`;
const SIGNING_CONFIGS_TO = `signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        release {
            storeFile file(BES_UPLOAD_STORE_FILE)
            storePassword BES_UPLOAD_STORE_PASSWORD
            keyAlias BES_UPLOAD_KEY_ALIAS
            keyPassword BES_UPLOAD_KEY_PASSWORD
        }
    }`;

const RELEASE_SIGNING_FROM = 'signingConfig signingConfigs.debug';
const RELEASE_SIGNING_TO = 'signingConfig signingConfigs.release';

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (config) => {
    if (!config.modResults.contents.includes(SIGNING_CONFIGS_FROM)) {
      throw new Error(
        `withReleaseSigning: expected to find the default debug-only ` +
          `signingConfigs block in android/app/build.gradle but it was not ` +
          `there — the generated template likely changed. Update this ` +
          `plugin instead of letting the release build silently stay ` +
          `debug-signed.`,
      );
    }
    config.modResults.contents = config.modResults.contents.replace(
      SIGNING_CONFIGS_FROM,
      SIGNING_CONFIGS_TO,
    );

    // Only the release buildType's signingConfig line should switch — the
    // debug buildType's own signingConfig.debug reference must stay as-is,
    // so replace just the second (release) occurrence.
    const firstIndex = config.modResults.contents.indexOf(RELEASE_SIGNING_FROM);
    const secondIndex = config.modResults.contents.indexOf(RELEASE_SIGNING_FROM, firstIndex + 1);
    if (firstIndex === -1 || secondIndex === -1) {
      throw new Error(
        `withReleaseSigning: expected two ${JSON.stringify(RELEASE_SIGNING_FROM)} ` +
          `occurrences (debug buildType, release buildType) in ` +
          `android/app/build.gradle, but found ${
            firstIndex === -1 ? 0 : secondIndex === -1 ? 1 : 2
          }. Update this plugin instead of letting the release build ` +
          `silently stay debug-signed.`,
      );
    }
    config.modResults.contents =
      config.modResults.contents.slice(0, secondIndex) +
      RELEASE_SIGNING_TO +
      config.modResults.contents.slice(secondIndex + RELEASE_SIGNING_FROM.length);

    return config;
  });
};
